formatter: markdown
header-from: main.tf
content: |-
  {{ .Header }}

  {{ .Providers }}

  {{ .Outputs }}

  {{ .Inputs }}

output: 
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true
